name: abdulai
description: Personal JARVIS AI Assistant with Real-time Caller ID
publish_to: 'none'
version: 3.0.0+3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  permission_handler: ^11.0.1
  flutter_phone_state: any
  flutter_background_service: ^5.0.5
  flutter_overlay_window: ^0.4.4
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
